CREATE TABLE answers (
	id BIGSERIAL PRIMARY KEY,
	question_id BIGSERIAL REFERENCES questions(id) ON DELETE CASCADE NOT NULL,
	body TEXT NOT NULL,
	is_correct BOOLEAN NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
