// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: copyfrom.go

package models

import (
	"context"
)

// iteratorForInsertAnswers implements pgx.CopyFromSource.
type iteratorForInsertAnswers struct {
	rows                 []InsertAnswersParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertAnswers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertAnswers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Body,
		r.rows[0].QuestionID,
		r.rows[0].IsCorrect,
	}, nil
}

func (r iteratorForInsertAnswers) Err() error {
	return nil
}

func (q *Queries) InsertAnswers(ctx context.Context, arg []InsertAnswersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"answers"}, []string{"body", "question_id", "is_correct"}, &iteratorForInsertAnswers{rows: arg})
}
