// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Answer struct {
	ID         int64
	QuestionID int64
	Body       string
	IsCorrect  bool
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type Question struct {
	ID        int64
	Body      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
